[package]
name = "beautyxt_rs"
version = "0.1.0"
edition = "2021"
license-file = "./LICENSE.txt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docx-rs = "0.4.7"
ego-tree = "0.6.2"
markdown = "1.0.0-alpha.12"
scraper = "0.17.1"
uniffi = { git = "https://github.com/mozilla/uniffi-rs", rev = "75919cc71be5ffd0e5089c10da00002295d7617d" }

[build-dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs", rev = "75919cc71be5ffd0e5089c10da00002295d7617d", features = ["build"] }

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[profile.release]
strip = true
lto = "fat"
codegen-units = 1

