[package]
name = "beautyxt_rs"
version = "0.1.0"
edition = "2021"
license = "ISC"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown = "1.0.0-alpha.11"
uniffi = { git = "https://github.com/mozilla/uniffi-rs", rev = "5598e0b6070eabc74cc1a3c8cafedd592e4a569f" }

[build-dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs", rev = "5598e0b6070eabc74cc1a3c8cafedd592e4a569f", features = ["build"] }

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[profile.release]
strip = true
lto = true
codegen-units = 1